version: '3.8'
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./backend/postgres:/var/lib/postgresql/data:z
    command: -p ${DB_PORT}
  backend:
    build: ./backend
    depends_on:
      - postgres
    image: backend:latest
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
  frontend:
    build: ./frontend
    depends_on:
      - backend
    image: frontend:latest
    environment:
      PORT: 3000
    ports:
      - 3000:3000
